#include "..\include\calculadoraVolumenAreaPerimetro.h"
#include <stdio.h>
int main(){
    float a = 23.43;
    float b = 34.32;
    float z = areaHexagono(a, b);
    printf ("El area del Hexagono es: %0.4f", z);
    printf("\n");
    a = 32.32;
    b = 45.65;
    z = areaRombo(a, b);
    printf ("El area del Rombo es: %0.4f", z);
    printf("\n");
    a = 56;
    z = perimetroHexagono(a);
    printf ("El perimetro del Hexagono es: %0.4f", z);
    printf("\n");
    a = 65.3;
    z = perimetroRombo(a);
    printf ("El perimetro del Rombo es: %0.4f", z);
    printf("\n");
    float x=4;
    float res= areaCirculo(x);
    printf("Area Circulo: %f", res);
    printf("\n");
    a= 11;
    float r = areaCuadrado (a);
    printf ("Area de Cuadrado es: %f", r);
    printf("\n");
    a=4.2;
    float area;
    area=areaPentagono(a);
    printf("Area pentagono: %f",area);
    printf("\n");
    a= 6;
    b =8;
    r =areaRectangulo(a, b);
    printf ("Area de Rectangulo es: %f", r);
    printf("\n");
    a=3.65;
    b=5.6;
    float h=24.5;
    area;
    area=areaTrapecio(a,b,h);
    printf("Area trapecio: %f",area);
    printf("\n");
    x=4;
    float y =9.1;
    res= areaTriangulo(x, y);
    printf("Area Triangulo: %f", res);
    printf("\n");
    x=6;
    res= perimetroCirculo(x);
    printf("Perimetro Circulo: %f", res);
    printf("\n");
    a= 45;
    r =perimetroCuadrado(a);
    printf ("Perimetro de Cuadrado es: %f", r);
    printf("\n");
    a=7.3;
    float peri=perimetroPentagono(a);
    printf("Perimetro pentagono: %f",peri);
    printf("\n");
    a= 15, b= 3;
    r = perimetroRectangulo(a,b);
    printf ("Perimetro de Rectangulo es: %f", r);
    printf("\n");
    a=10.7;
    b=8.9;
    float c=8.9;
    float d= 4.5;
    peri=perimetroTrapecio(a,b,c,d);
    printf("Perimetro trapecio: %f",peri);
    printf("\n");
    x=4;
    res= perimetroTriangulo(x);
    printf("Perimetro Triangulo: %f", res);
    printf("\n");
    a= 24;
    r =volumenCubo(a);
    printf ("El volumen del cubo es: %f", r);
    printf("\n");
    a=5.8;
    h=16.8;
    float vol=volumenPiramideCuadrangular(a,h);
    printf("Volumen piramide cuadrangular: %f", vol);
    printf("\n");

    a=6.7;
    h=24.8;
    vol=volumenPiramideHexagonal(a,h);
    printf("Volumen piramide hexagonal: %f",vol);
    printf("\n");
    a=8.5;
    h=16.3;
    vol=volumenPiramidePentagonal(a,h);
    printf("Volumen piramide pentagonal: %f",vol);
    printf("\n");

    b=4, h=3;
    float H=8;
    res= volumenPiramideTriangular(b,h,H);
    printf("Volumen Piramide Triangular : %f", res);
    printf("\n");
    a=10, b=45, c=8;
    r =volumenPrismaCuadrangular(a,b,c);
    printf ("El volumen de un prisma cuadrangular es: %f", r);
    printf("\n");
    float l=4;
    H=22.5;
    res= volumenPrismaHexagonal(l, H);
    printf("Volumen Prisma Hexagonal: %f", res);
    printf("\n");
    l=4, H=31.3;
    res= volumenPrismaPentagonal(l, H);
    printf("Volumen Prisma Pentagonal c: %f", res);
    printf("\n");
    a= 11, b=16, c=6 ;
    r =volumenPrismaTriangular(a,b,c);
    printf ("El volumen de un Prisma Triangular es: %f", r);
    printf("\n");
    a = 54.2;
    b = 16.3;
    z = volumenCilindro(a, b);
    printf ("El volumen del Cilindro es: %0.4f", z);
    printf("\n");
    a = 7.2;
    b = 23.78;
    z = volumenCono(a, b);
    printf ("El volumen del Cono es: %0.4f", z);
    printf("\n");
    a = 6.34;
    z = volumenEsfera(a);
    printf ("El volumen de la esfera es: %0.4f", z);
    printf("\n");
    return 0;
}