#include "..\include\calculadoraVolumenAreaPerimetro.h"
#include <stdio.h>
int main(){
    float a = 31.20;
    float b = 42.6;
    float z = areaHexagono(a, b);
    printf ("El area del Hexagono es: %0.4f", z);
    printf("\n");
    a = 13.13;
    b = 54.32;
    z = areaRombo(a, b);
    printf ("El area del Rombo es: %0.4f", z);
    printf("\n");
    a = 47;
    z = perimetroHexagono(a);
    printf ("El perimetro del Hexagono es: %0.4f", z);
    printf("\n");
    a = 68.95;
    z = perimetroRombo(a);
    printf ("El perimetro del Rombo es: %0.4f", z);
    printf("\n");
    float x=11;
    float res= areaCirculo(x);
    printf("Area Circulo: %f", res);
    printf("\n");
    a= 98;
    float r = areaCuadrado (a);
    printf ("Area de Cuadrado es: %f", r);
    printf("\n");
    a=15;
    float area;
    area=areaPentagono(a);
    printf("Area pentagono: %f",area);
    printf("\n");
    a= 3;
    b =8;
    r =areaRectangulo(a, b);
    printf ("Area de Rectangulo es: %f", r);
    printf("\n");
    a=10.65;
    b=47.6;
    float h=24.5;
    area;
    area=areaTrapecio(a,b,h);
    printf("Area trapecio: %f",area);
    printf("\n");
    x=109;
    float y =15.6;
    res= areaTriangulo(x, y);
    printf("Area Triangulo: %f", res);
    printf("\n");
    x=52;
    res= perimetroCirculo(x);
    printf("Perimetro Circulo: %f", res);
    printf("\n");
    a= 3;
    r =perimetroCuadrado(a);
    printf ("Perimetro de Cuadrado es: %f", r);
    printf("\n");
    a=14.3;
    float peri=perimetroPentagono(a);
    printf("Perimetro pentagono: %f",peri);
    printf("\n");
    a= 25, b= 56;
    r = perimetroRectangulo(a,b);
    printf ("Perimetro de Rectangulo es: %f", r);
    printf("\n");
    a=10.7;
    b=8.9;
    float c=8.9;
    float d= 4.5;
    peri=perimetroTrapecio(a,b,c,d);
    printf("Perimetro trapecio: %f",peri);
    printf("\n");
    x=36;
    res= perimetroTriangulo(x);
    printf("Perimetro Triangulo: %f", res);
    printf("\n");
    a= 21;
    r =volumenCubo(a);
    printf ("El volumen del cubo es: %f", r);
    printf("\n");
    a=4.66;
    h=19.88;
    float vol=volumenPiramideCuadrangular(a,h);
    printf("Volumen piramide cuadrangular: %f", vol);
    printf("\n");

    a=15;
    h=30;
    vol=volumenPiramideHexagonal(a,h);
    printf("Volumen piramide hexagonal: %f",vol);
    printf("\n");
    a=8;
    h=16.36;
    vol=volumenPiramidePentagonal(a,h);
    printf("Volumen piramide pentagonal: %f",vol);
    printf("\n");

    b=6, h=12;
    float H=8;
    res= volumenPiramideTriangular(b,h,H);
    printf("Volumen Piramide Triangular : %f", res);
    printf("\n");
    a=15, b=23, c=7;
    r =volumenPrismaCuadrangular(a,b,c);
    printf ("El volumen de un prisma cuadrangular es: %f", r);
    printf("\n");
    float l=6;
    H=23.6;
    res= volumenPrismaHexagonal(l, H);
    printf("Volumen Prisma Hexagonal: %f", res);
    printf("\n");
    l=37, H=65;
    res= volumenPrismaPentagonal(l, H);
    printf("Volumen Prisma Pentagonal c: %f", res);
    printf("\n");
    a=65, b=45, c=25 ;
    r =volumenPrismaTriangular(a,b,c);
    printf ("El volumen de un Prisma Triangular es: %f", r);
    printf("\n");
    a = 33.45;
    b = 96.12;
    z = volumenCilindro(a, b);
    printf ("El volumen del Cilindro es: %0.4f", z);
    printf("\n");
    a = 23.45;
    b = 56.2;
    z = volumenCono(a, b);
    printf ("El volumen del Cono es: %0.4f", z);
    printf("\n");
    a = 45;
    z = volumenEsfera(a);
    printf ("El volumen de la esfera es: %0.4f", z);
    printf("\n");
    return 0;
     
}